require: rubocop-rails

AllCops:
  NewCops: enable

Layout/LineLength:
  Exclude:
    - config/initializers/devise.rb
    - db/seeds.rb

Metrics/AbcSize:
  Exclude:
    - app/controllers/reviews_controller.rb

Metrics/MethodLength:
  Exclude:
    - app/controllers/reviews_controller.rb
    - db/migrate/20210116190828_create_active_storage_tables.active_storage.rb

Style/Documentation:
  Enabled: false