default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: media_critic_development

test:
  <<: *default
  database: media_critic_test

production:
  <<: *default
  database: media_critic_production
  username: media_critic
  password: <%= ENV['MEDIA_CRITIC_DATABASE_PASSWORD'] %>
